ports:
- port: 9001
- port: 8080
tasks:
- init: poetry install
- init : docker pull siegfried415/portia-dashboard
- command: docker run -v ~/portia_projects:/app/data/projects:rw -p 9001:9001 siegfried415/portia-dashboard start-dev 

